export default {
  "Getting started": [
    ["Installation", "/docs/installation"],
    ["Editor setup", "/docs/editor-setup"],
    ["Compatibility", "/docs/compatibility"],
    ["Upgrade guide", "/docs/upgrade-guide"],
  ] as const,
  "Core concepts": [
    ["Styling with utility classes", "/docs/styling-with-utility-classes"],
    ["Hover, focus, and other states", "/docs/hover-focus-and-other-states"],
    ["Responsive design", "/docs/responsive-design"],
    ["Dark mode", "/docs/dark-mode"],
    ["Theme variables", "/docs/theme"],
    ["Colors", "/docs/colors"],
    ["Adding custom styles", "/docs/adding-custom-styles"],
    ["Detecting classes in source files", "/docs/detecting-classes-in-source-files"],
    ["Functions and directives", "/docs/functions-and-directives"],
  ] as const,
  "Base styles": [["Preflight", "/docs/preflight"]] as const,
  Layout: [
    ["aspect-ratio", "/docs/aspect-ratio"],
    ["columns", "/docs/columns"],
    ["break-after", "/docs/break-after"],
    ["break-before", "/docs/break-before"],
    ["break-inside", "/docs/break-inside"],
    ["box-decoration-break", "/docs/box-decoration-break"],
    ["box-sizing", "/docs/box-sizing"],
    ["display", "/docs/display"],
    ["float", "/docs/float"],
    ["clear", "/docs/clear"],
    ["isolation", "/docs/isolation"],
    ["object-fit", "/docs/object-fit"],
    ["object-position", "/docs/object-position"],
    ["overflow", "/docs/overflow"],
    ["overscroll-behavior", "/docs/overscroll-behavior"],
    ["position", "/docs/position"],
    ["top / right / bottom / left", "/docs/top-right-bottom-left"],
    ["visibility", "/docs/visibility"],
    ["z-index", "/docs/z-index"],
  ] as const,
  "Flexbox & Grid": [
    ["flex-basis", "/docs/flex-basis"],
    ["flex-direction", "/docs/flex-direction"],
    ["flex-wrap", "/docs/flex-wrap"],
    ["flex", "/docs/flex"],
    ["flex-grow", "/docs/flex-grow"],
    ["flex-shrink", "/docs/flex-shrink"],
    ["order", "/docs/order"],
    ["grid-template-columns", "/docs/grid-template-columns"],
    ["grid-column", "/docs/grid-column"],
    ["grid-template-rows", "/docs/grid-template-rows"],
    ["grid-row", "/docs/grid-row"],
    ["grid-auto-flow", "/docs/grid-auto-flow"],
    ["grid-auto-columns", "/docs/grid-auto-columns"],
    ["grid-auto-rows", "/docs/grid-auto-rows"],
    ["gap", "/docs/gap"],
    ["justify-content", "/docs/justify-content"],
    ["justify-items", "/docs/justify-items"],
    ["justify-self", "/docs/justify-self"],
    ["align-content", "/docs/align-content"],
    ["align-items", "/docs/align-items"],
    ["align-self", "/docs/align-self"],
    ["place-content", "/docs/place-content"],
    ["place-items", "/docs/place-items"],
    ["place-self", "/docs/place-self"],
  ] as const,
  Spacing: [
    ["padding", "/docs/padding"],
    ["margin", "/docs/margin"],
  ] as const,
  Sizing: [
    ["width", "/docs/width"],
    ["min-width", "/docs/min-width"],
    ["max-width", "/docs/max-width"],
    ["height", "/docs/height"],
    ["min-height", "/docs/min-height"],
    ["max-height", "/docs/max-height"],
  ] as const,
  Typography: [
    ["font-family", "/docs/font-family"],
    ["font-size", "/docs/font-size"],
    ["font-smoothing", "/docs/font-smoothing"],
    ["font-style", "/docs/font-style"],
    ["font-weight", "/docs/font-weight"],
    ["font-stretch", "/docs/font-stretch"],
    ["font-variant-numeric", "/docs/font-variant-numeric"],
    ["letter-spacing", "/docs/letter-spacing"],
    ["line-clamp", "/docs/line-clamp"],
    ["line-height", "/docs/line-height"],
    ["list-style-image", "/docs/list-style-image"],
    ["list-style-position", "/docs/list-style-position"],
    ["list-style-type", "/docs/list-style-type"],
    ["text-align", "/docs/text-align"],
    ["color", "/docs/color"],
    ["text-decoration-line", "/docs/text-decoration-line"],
    ["text-decoration-color", "/docs/text-decoration-color"],
    ["text-decoration-style", "/docs/text-decoration-style"],
    ["text-decoration-thickness", "/docs/text-decoration-thickness"],
    ["text-underline-offset", "/docs/text-underline-offset"],
    ["text-transform", "/docs/text-transform"],
    ["text-overflow", "/docs/text-overflow"],
    ["text-wrap", "/docs/text-wrap"],
    ["text-indent", "/docs/text-indent"],
    ["vertical-align", "/docs/vertical-align"],
    ["white-space", "/docs/white-space"],
    ["word-break", "/docs/word-break"],
    ["overflow-wrap", "/docs/overflow-wrap"],
    ["hyphens", "/docs/hyphens"],
    ["content", "/docs/content"],
  ] as const,
  Backgrounds: [
    ["background-attachment", "/docs/background-attachment"],
    ["background-clip", "/docs/background-clip"],
    ["background-color", "/docs/background-color"],
    ["background-image", "/docs/background-image"],
    ["background-origin", "/docs/background-origin"],
    ["background-position", "/docs/background-position"],
    ["background-repeat", "/docs/background-repeat"],
    ["background-size", "/docs/background-size"],
  ] as const,
  Borders: [
    ["border-radius", "/docs/border-radius"],
    ["border-width", "/docs/border-width"],
    ["border-color", "/docs/border-color"],
    ["border-style", "/docs/border-style"],
    ["outline-width", "/docs/outline-width"],
    ["outline-color", "/docs/outline-color"],
    ["outline-style", "/docs/outline-style"],
    ["outline-offset", "/docs/outline-offset"],
  ] as const,
  Effects: [
    ["box-shadow", "/docs/box-shadow"],
    ["text-shadow", "/docs/text-shadow"],
    ["opacity", "/docs/opacity"],
    ["mix-blend-mode", "/docs/mix-blend-mode"],
    ["background-blend-mode", "/docs/background-blend-mode"],
    ["mask-clip", "/docs/mask-clip"],
    ["mask-composite", "/docs/mask-composite"],
    ["mask-image", "/docs/mask-image"],
    ["mask-mode", "/docs/mask-mode"],
    ["mask-origin", "/docs/mask-origin"],
    ["mask-position", "/docs/mask-position"],
    ["mask-repeat", "/docs/mask-repeat"],
    ["mask-size", "/docs/mask-size"],
    ["mask-type", "/docs/mask-type"],
  ] as const,
  Filters: [
    [
      "filter",
      "/docs/filter",
      [
        ["blur", "/docs/filter-blur"],
        ["brightness", "/docs/filter-brightness"],
        ["contrast", "/docs/filter-contrast"],
        ["drop-shadow", "/docs/filter-drop-shadow"],
        ["grayscale", "/docs/filter-grayscale"],
        ["hue-rotate", "/docs/filter-hue-rotate"],
        ["invert", "/docs/filter-invert"],
        ["saturate", "/docs/filter-saturate"],
        ["sepia", "/docs/filter-sepia"],
      ] as const,
    ] as const,
    [
      "backdrop-filter",
      "/docs/backdrop-filter",
      [
        ["blur", "/docs/backdrop-filter-blur"],
        ["brightness", "/docs/backdrop-filter-brightness"],
        ["contrast", "/docs/backdrop-filter-contrast"],
        ["grayscale", "/docs/backdrop-filter-grayscale"],
        ["hue-rotate", "/docs/backdrop-filter-hue-rotate"],
        ["invert", "/docs/backdrop-filter-invert"],
        ["opacity", "/docs/backdrop-filter-opacity"],
        ["saturate", "/docs/backdrop-filter-saturate"],
        ["sepia", "/docs/backdrop-filter-sepia"],
      ] as const,
    ] as const,
  ] as const,
  Tables: [
    ["border-collapse", "/docs/border-collapse"],
    ["border-spacing", "/docs/border-spacing"],
    ["table-layout", "/docs/table-layout"],
    ["caption-side", "/docs/caption-side"],
  ] as const,
  "Transitions & Animation": [
    ["transition-property", "/docs/transition-property"],
    ["transition-behavior", "/docs/transition-behavior"],
    ["transition-duration", "/docs/transition-duration"],
    ["transition-timing-function", "/docs/transition-timing-function"],
    ["transition-delay", "/docs/transition-delay"],
    ["animation", "/docs/animation"],
  ] as const,
  Transforms: [
    ["backface-visibility", "/docs/backface-visibility"],
    ["perspective", "/docs/perspective"],
    ["perspective-origin", "/docs/perspective-origin"],
    ["rotate", "/docs/rotate"],
    ["scale", "/docs/scale"],
    ["skew", "/docs/skew"],
    ["transform", "/docs/transform"],
    ["transform-origin", "/docs/transform-origin"],
    ["transform-style", "/docs/transform-style"],
    ["translate", "/docs/translate"],
  ] as const,
  Interactivity: [
    ["accent-color", "/docs/accent-color"],
    ["appearance", "/docs/appearance"],
    ["caret-color", "/docs/caret-color"],
    ["color-scheme", "/docs/color-scheme"],
    ["cursor", "/docs/cursor"],
    ["field-sizing", "/docs/field-sizing"],
    ["pointer-events", "/docs/pointer-events"],
    ["resize", "/docs/resize"],
    ["scroll-behavior", "/docs/scroll-behavior"],
    ["scroll-margin", "/docs/scroll-margin"],
    ["scroll-padding", "/docs/scroll-padding"],
    ["scroll-snap-align", "/docs/scroll-snap-align"],
    ["scroll-snap-stop", "/docs/scroll-snap-stop"],
    ["scroll-snap-type", "/docs/scroll-snap-type"],
    ["touch-action", "/docs/touch-action"],
    ["user-select", "/docs/user-select"],
    ["will-change", "/docs/will-change"],
  ] as const,
  SVG: [
    ["fill", "/docs/fill"],
    ["stroke", "/docs/stroke"],
    ["stroke-width", "/docs/stroke-width"],
  ] as const,
  Accessibility: [["forced-color-adjust", "/docs/forced-color-adjust"]] as const,
};
